# fly.toml app configuration file generated for video-sinc on 2023-09-06T21:23:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "video-sinc"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
